cookie:
  secret: "change_me"
  domain: ".domain.com"

auth_domain: "auth.domain.com"

allowed_email_domains:
  - domain@domain.com

allowed_email: 
  - user@gmail.com

routing:
  graphite.domain.com: http://graphite.lxc
